/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b55aeb8f-b22a-455f-a79d-da0f42127b61",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tcdrugVde",
    "aws_user_pools_web_client_id": "34d15q2jfvi3nb8tdvqg7vc0ee",
    "oauth": {
        "domain": "wgjyf0lgln1c-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://wgjyf0lgln1c-staging.auth.us-east-2.amazoncognito.com/oauth2/idpresponse",
        "redirectSignOut": "https://wgjyf0lgln1c-staging.auth.us-east-2.amazoncognito.com/oauth2/idpresponse",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
